serenity.project.name=Serenity QA Innovation Lab Mobile
serenity.take.screenshots=AFTER_EACH_STEP
appium.hub=http://localhost:4723/

#---------------Android capabilities---------------#
appium.platformName=Android
appium.automationName=uiautomator2

#Cambiar el nombre del dispositivo conectado o emulado, se puede obtener con el comando "adb devices"
appium.deviceName=emulator-5554

#Es el identificador único en todo de la app
appium.package=com.saucelabs.mydemoapp.android
#Abre la app que está en esta dirección es package + activity
appium.appActivity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity

#Esta linea instala la app desde el directorio de recursos cada vez que se ejecuta el test
#RECOMENDACION es comentarla si la app ya esta instalada en el dispositivo
#appium.app=${user.dir}/src/test/resources/app/mda-2.0.2-23.apk
